[package]
name = "util"
version.workspace = true
edition.workspace = true
description = "Shared parsing utilities for CarParser"
license.workspace = true
repository.workspace = true
readme.workspace = true
publish = false

[lib]
name = "util"

[dependencies]
deku = { workspace = true }
lzfse_rust = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
