[package]
name = "car-cli"
version.workspace = true
edition.workspace = true

[features]
default = ["image"]
image = ["car/image"]

[dependencies]
car = { path = "../car", default-features = false }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
test-support = { path = "../test-support" }
image = { workspace = true }
